on: [push, pull_request]

name: Lint and Build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      run: npm ci
    - name: Build
      run: npm run build chrome
    - name: Lint
      run: npm run lint
