on: [push, pull_request]

name: Lint and Build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: npm ci
    - run: npm run build chrome
    - run: npm run lint
